### ISSUE TITLE
can't run the example

### ISSUE THREAD

**Issue by despiegk** [tsedio/tsed-getting-started#84]
```
/Users/despiegk/code2/tsed-getting-started/node_modules/ts-node/src/index.ts:692
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/middlewares/GlobalErrorHandlerMiddleware.ts:37:16 - error TS2339: Property 'status' does not exist on type 'Res'.

37       response.status(404).send(toHTML(error));
                  ~~~~~~
src/middlewares/GlobalErrorHandlerMiddleware.ts:62:8 - error TS2339: Property 'set' does not exist on type 'Res'.

62       .set(getHeaders(error))
          ~~~
src/middlewares/GlobalErrorHandlerMiddleware.ts:74:8 - error TS2339: Property 'set' does not exist on type 'Res'.

74       .set(getHeaders(error))
          ~~~

    at createTSError (/Users/despiegk/code2/tsed-getting-started/node_modules/ts-node/src/index.ts:692:12)
    at reportTSError (/Users/despiegk/code2/tsed-getting-started/node_modules/ts-node/src/index.ts:696:19)
    at getOutput (/Users/despiegk/code2/tsed-getting-started/node_modules/ts-node/src/index.ts:883:36)
    at Object.compile (/Users/despiegk/code2/tsed-getting-started/node_modules/ts-node/src/index.ts:1185:30)
    at Module.m._compile (/Users/despiegk/code2/tsed-getting-started/node_modules/ts-node/src/index.ts:1309:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/despiegk/code2/tsed-getting-started/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticText: "\x1B[96msrc/middlewares/GlobalErrorHandlerMiddleware.ts\x1B[0m:\x1B[93m37\x1B[0m:\x1B[93m16\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'status' does not exist on type 'Res'.\n" +
    '\n' +
    '\x1B[7m37\x1B[0m       response.status(404).send(toHTML(error));\n' +
    '\x1B[7m  \x1B[0m \x1B[91m               ~~~~~~\x1B[0m\n' +
    "\x1B[96msrc/middlewares/GlobalErrorHandlerMiddleware.ts\x1B[0m:\x1B[93m62\x1B[0m:\x1B[93m8\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'set' does not exist on type 'Res'.\n" +
    '\n' +
    '\x1B[7m62\x1B[0m       .set(getHeaders(error))\n' +
    '\x1B[7m  \x1B[0m \x1B[91m       ~~~\x1B[0m\n' +
    "\x1B[96msrc/middlewares/GlobalErrorHandlerMiddleware.ts\x1B[0m:\x1B[93m74\x1B[0m:\x1B[93m8\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'set' does not exist on type 'Res'.\n" +
    '\n' +
    '\x1B[7m74\x1B[0m       .set(getHeaders(error))\n' +
    '\x1B[7m  \x1B[0m \x1B[91m       ~~~\x1B[0m\n',
  diagnosticCodes: [ 2339, 2339, 2339 ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

am on OSX M.1

**Comment by Romakita** [comment]
Hello @despiegk 
Thanks for the feedback. You can use the CLI
to generate a project instead :)

npm i -g @tsed/cli
tsed init .
